/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sanik
 */
public class UpdateInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateInformationJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    String user;
   // List userList = new ArrayList();
    String username;
    
    public UpdateInformationJPanel(JPanel userProcessContainer, EcoSystem system, String user, String username) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;
        this.username = username;
        this.populateData();
        this.usernameTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JPasswordField();
        usernameTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Username");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 102, -1, -1));

        jLabel3.setText("Password ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 140, -1, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 178, -1, -1));
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 175, 138, -1));

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });
        add(passwordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 137, 136, -1));
        add(usernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 99, 136, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 235, -1, -1));

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 235, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Update Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void populateData() {
        
        usernameTextField.setText(this.username);
        if(this.user.equals("Customer"))
        {
//            for(Customer c: system.getCustomerDirectory().getCustomerList())
//            {
//                if(c.getUsername().equals(this.username))
//                {
//                    Customer cust = c;
//                    nameTextField.setText(cust.getName());
//                }
//            }
//            
//            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
//            {
//                if(ua.getUsername().equals(this.username))
//                {
//                    UserAccount userAccount = ua;
//                    passwordTextField.setText(userAccount.getPassword());
//                }
//            }
        }
        else if(this.user.equals("DeliveryMan"))
        {
           for(DeliveryMan d: system.getDeliveryManDirectory().getDeliverymanList())
            {
                if(d.getUsername().equals(this.username))
                {
                    DeliveryMan dm = d;
                    nameTextField.setText(dm.getName());
                }
            }
            
            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
            {
                if(ua.getUsername().equals(this.username))
                {
                    UserAccount userAccount = ua;
                    passwordTextField.setText(userAccount.getPassword());
                }
            }
        }
        else
        {
            for(Restaurant r: system.getRestaurantDirectory().getRestaurantList())
            {
                if(r.getRestaurantAdminUsername().equals(this.username))
                {
                    Restaurant cust = r;
                    nameTextField.setText(cust.getName());
                }
            }
           
            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
            {
                if(ua.getUsername().equals(this.username))
                {
                    UserAccount userAccount = ua;
                    passwordTextField.setText(userAccount.getPassword());
                }
            }
        }

    }
    
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        if(this.user.equals("DeliveryMan"))
        {
            ManageDeliveryManJPanel manageDeliveryManJPanel = (ManageDeliveryManJPanel) component;
            manageDeliveryManJPanel.populateTable(); 
        }
        else if(this.user.equals("Restaurant"))
        {
            ManageRestaurantsJPanel manageRestaurantsJPanel = (ManageRestaurantsJPanel) component;
            manageRestaurantsJPanel.populateTable(); 
        }
        else
        {
            ManageAllCustomersJPanel manageAllCustomersJPanel = (ManageAllCustomersJPanel) component;
            manageAllCustomersJPanel.populateTable(); 
        }
        
   

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
       
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
         String name = nameTextField.getText();
         String password = String.valueOf(passwordTextField.getPassword());
        if(this.user.equals("Customer"))
        {
//           for(Customer c: system.getCustomerDirectory().getCustomerList())
//            {
//                if(c.getUsername().equals(this.username))
//                {
//                    Customer cust = c;
//                    cust.setName(nameTextField.getText());
//                }
//            }
//            
//            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
//            {
//                if(ua.getUsername().equals(this.username))
//                {
//                    UserAccount userAccount = ua;
//                    ua.setPassword(password);
//                }
//            }
//            JOptionPane.showMessageDialog(null, "Customer updated succesfully");
//            nameTextField.setText("");
//            passwordTextField.setText("");
//            usernameTextField.setText("");
        }
        else if(this.user.equals("DeliveryMan"))
        {
            DeliveryMan d = null;
            for(DeliveryMan dm: system.getDeliveryManDirectory().getDeliverymanList()) 
            {
                if(dm.getUsername().equals(this.username))
                {
                    d = dm;
                    d.setName(name);
                    break;
                }
            }
            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
            {
                if(ua.getUsername().equals(this.username))
                {
                    UserAccount userAccount = ua;
                    userAccount.setPassword(password);
                    break;
                }
            }
            String name1 = d.getName();
            for(Employee emp: system.getEmployeeDirectory().getEmployeeList())
            {
                if(name1.equals(emp.getName()))
                {
                            emp.setName(name);
                }
            }
            JOptionPane.showMessageDialog(null, "Delivery Man updated successfully");
        }
        else
        {
            for (Restaurant r:system.getRestaurantDirectory().getRestaurantList())
            {
                if(r.getRestaurantAdminUsername().equals (this.username))
                {
                    Restaurant cust =r;
                    cust.setName(nameTextField.getText());
                }
            }
            for(UserAccount ua: system.getUserAccountDirectory().getUserAccountList())
            {
                if(ua.getUsername().equals(this.username))
                {UserAccount userAccount = ua;
                ua.setPassword(password);
            }
        }
            JOptionPane.showMessageDialog(null,"Restaurant information updated successfully");
        }
        nameTextField.setText("");
        passwordTextField.setText("");
        usernameTextField.setText("");
        System.out.println("Print" + system.getEmployeeDirectory().getEmployeeList());

    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
