package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.ManageDeliveryManJPanel;

/**
 *
 * @author Sanik
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Restaurant restaurant;
    EcoSystem system;
    UserAccount userAccount;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Restaurant restaurant, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurant = restaurant;
        this.system = system;
        this.userAccount = userAccount;
        valueLabel.setText(this.restaurant.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btncustomers = new javax.swing.JButton();
        btnrestaurants = new javax.swing.JButton();
        btndeliveryman = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 5, 580, 50));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterpriseLabel.setText("Restaurant :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 80, 30));

        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 130, -1));

        btncustomers.setText("Restaurant Menu");
        btncustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomersActionPerformed(evt);
            }
        });
        add(btncustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        btnrestaurants.setText("Orders");
        btnrestaurants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestaurantsActionPerformed(evt);
            }
        });
        add(btnrestaurants, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        btndeliveryman.setText("Manage all Deliverman");
        btndeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeliverymanActionPerformed(evt);
            }
        });
        add(btndeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageRestaurantInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageRestaurantInfoActionPerformed
        // TODO add your handling code here:
//        ManageRestaurantInfoJPanel manageRestaurantInfoJPanel = new ManageRestaurantInfoJPanel(userProcessContainer, restaurant);
//        userProcessContainer.add("manageRestaurantJPanel", manageRestaurantInfoJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageRestaurantInfoActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        
    }//GEN-LAST:event_btnManageMenuActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
       
    }//GEN-LAST:event_btnManageOrdersActionPerformed

    private void btncustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomersActionPerformed
        // TODO add your handling code here:
        ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer, restaurant);
        userProcessContainer.add("manageMenuJPanel", manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btncustomersActionPerformed

    private void btnrestaurantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestaurantsActionPerformed
        // TODO add your handling code here:
        ManageOrdersJPanel manageOrdersJPanel = new ManageOrdersJPanel(userProcessContainer, this.restaurant, this.system.getDeliveryManDirectory(), this.userAccount);
        userProcessContainer.add("manageOrdersJPanel", manageOrdersJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnrestaurantsActionPerformed

    private void btndeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeliverymanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeliverymanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncustomers;
    private javax.swing.JButton btndeliveryman;
    private javax.swing.JButton btnrestaurants;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
