/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sanik
 */
public class AssignToDeliverymanJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignToDeliverymanJPanel
     */
    JPanel userProcessContainer;
    Order order;
    UserAccount userAccount;
    Restaurant restaurant;
    DeliveryManDirectory deliveryManDirectory;
    public AssignToDeliverymanJPanel(JPanel userProcessContainer, Order order, DeliveryManDirectory deliveryManDirectory, Restaurant restaurant, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.order = order;
        this.deliveryManDirectory = deliveryManDirectory;
        this.restaurant = restaurant;
        this.userAccount = userAccount;
        dpdDeliveryman.removeAllItems();
        this.populateDeliveryMan();
        orderIdTextField.setEditable(false);
        orderIdTextField.setText(Integer.toString(this.order.getOrderId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void populateDeliveryMan()
    {
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            dpdDeliveryman.addItem(d.getName());
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        dpdDeliveryman = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        orderIdTextField = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Select DeliveryMan:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 109, -1, -1));

        dpdDeliveryman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dpdDeliveryman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpdDeliverymanActionPerformed(evt);
            }
        });
        add(dpdDeliveryman, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 106, 169, -1));

        jLabel1.setText("Order id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 150, -1, -1));

        orderIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdTextFieldActionPerformed(evt);
            }
        });
        add(orderIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 147, 169, -1));

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 196, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Assign  Order to Delivery Man");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 436, -1));

        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 196, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void dpdDeliverymanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpdDeliverymanActionPerformed
        
    }//GEN-LAST:event_dpdDeliverymanActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your h)andling code here:
        DeliveryMan dm = null;
        String d1 = (String)dpdDeliveryman.getSelectedItem();
        for(DeliveryMan d: this.deliveryManDirectory.getDeliverymanList())
        {
            if(d.getName().equals(d1))
            {
                dm = d;
            }
        }
        for (WorkRequest w : this.restaurant.getWorkQueue().getWorkRequestList()) 
            {
                if((w.getOrder() != null) && (w.getOrder().getOrderId() == order.getOrderId()))
                {
                   w.setSender(this.userAccount);
                   w.setStatus("Assinged to delivery Man");
                    JOptionPane.showMessageDialog(this,"Assinged to delivery Man");
                   dm.getWorkQueue().getWorkRequestList().add(w);
                   System.out.println("d work " + dm.getWorkQueue().getWorkRequestList());
                   break;
                }
  
            }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void orderIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderIdTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox<String> dpdDeliveryman;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField orderIdTextField;
    // End of variables declaration//GEN-END:variables
}
